export const WINDOW_CART = "WINDOW_CART"
export const WINDOW_USER = "WINDOW_USER"
export const WINDOW_SEARCH = "WINDOW_SEARCH"
export const WINDOW_HOME = "WINDOW_HOME"
export const WINDOW_MENU = "WINDOW_MENU"

export const WINDOW_IS_USER_LOGIN = "WINDOW_IS_USER_LOGIN"
export const WINDOW_IS_USER_SIGNUP = "WINDOW_IS_USER_SIGNUP"
export const WINDOW_IS_USER_PROFILE = "WINDOW_IS_USER_PROFILE"

export const WINDOW_IS_MENU = "WINDOW_IS_MENU"
export const WINDOW_IS_SEARCH = "WINDOW_IS_SEARCH"

