export const ADD_TO_CART = "ADD_TO_CART";

export const DECRIMENT_TO_CART = "DECRIMENT_TO_CART";

export const DELETE_PRODUCT = "DELETE_PRODUCT";

export const DELETE_ALL_PRODUCT = "DELETE_ALL_PRODUCT";