export const USER_REQUEST = "USER_REQUEST";

export const USER_SUCCESS = "USER_SUCCESS";

export const USER_FAILURE = "USER_FAILURE";

export const USER_AUTOMATIC = "USER_AUTOMATIC";

export const USER_REMMEMBER = "USER_REMMEMBER";

export const USER_LOGOUT = "USER_LOGOUT";